name: Registrar Usuario y Crear Estructura en Main

on:
  push:
    branches:
      - visitante
    paths:
      - "registro.yaml" # Detecta cambios en este archivo.

jobs:
  register-user:
    runs-on: ubuntu-latest

    steps:
      # 1. Revisa los cambios en la rama `visitante`.
      - name: Checkout rama visitante
        uses: actions/checkout@v3
        with:
          ref: visitante

      - name: Validar Archivo de Registro
        run: |
          if [ ! -f "registro.yaml" ]; then
            echo "No se encontró registro.yaml, saliendo..."
            exit 1
          fi
          echo "Archivo registro.yaml encontrado, procesando..."

      # 2. Extrae los datos del archivo registro.yaml
      - name: Leer datos de registro
        id: registro
        run: |
          NOMBRE=$(grep "nombre:" registro.yaml | awk -F'"' '{print $2}')
          FECHA=$(grep "fecha_registro:" registro.yaml | awk -F'"' '{print $2}')
          echo "::set-output name=nombre::$NOMBRE"
          echo "::set-output name=fecha::$FECHA"

      # 3. Cambiar a la rama `main` y crear la estructura del usuario.
      - name: Checkout rama main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Crear estructura del usuario en Main
        run: |
          mkdir -p Usuarios/${{ steps.registro.outputs.nombre }}
          echo "## 📖 Perfil de Usuario" > Usuarios/${{ steps.registro.outputs.nombre }}/Perfil.md
          echo "- **Nombre:** ${{ steps.registro.outputs.nombre }}" >> Usuarios/${{ steps.registro.outputs.nombre }}/Perfil.md
          echo "- **📅 Fecha de Registro:** ${{ steps.registro.outputs.fecha }}" >> Usuarios/${{ steps.registro.outputs.nombre }}/Perfil.md
          echo "- **📚 Libros Leídos:** 0" >> Usuarios/${{ steps.registro.outputs.nombre }}/Perfil.md
          echo "- **📖 Libros Pendientes:** 0" >> Usuarios/${{ steps.registro.outputs.nombre }}/Perfil.md

      # 4. Confirmar los cambios.
      - name: Subir cambios a main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Añadido nuevo usuario: ${{ steps.registro.outputs.nombre }}"
          git push origin main
